name: ${project.name}
version: ${project.version}
api-version: 1.13

main: mc.alk.tracker.Tracker


author: alkarin
softdepend: [BattleCore, Essentials, Herochat, TownyChat]
description: A tracker for PvP player related events with leaderboard signs.  Includes database backend.
commands:
    battleTracker:
        aliases: [bt]
        description: Show help menu
        usage: /bt
    btpvp:
        aliases: [pvp]
        description: Show how players have matched up
        usage: /pvp player1 [player2]
    btpve:
        aliases: [pve]
        description: Show how players have matched up vs mobs/environment
        usage: /pve player1 [player2]
    
